An alternative corner detector to Harris is the FAST corner detector. There are a number of implementations inlcuding a pure Python version available at http://www.edwardrosten.com/work/fast.html. Try this detector, play with the sensitivity threshold, and compare the corners with the ones from our Harris implementation.

In [1]:
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
import fast

In [2]:
im1 = np.array(Image.open('../../data/alcatraz1.jpg').convert('L'))
im2 = np.array(Image.open('../../data/alcatraz2.jpg').convert('L'))

In [4]:
fast.get_fast_candidates(im1, 0)

[array([[ 0,  3],
        [ 1,  3],
        [ 2,  2],
        [ 3,  1],
        [ 3,  0],
        [ 3, -1],
        [ 2, -2],
        [ 1, -3],
        [ 0, -3],
        [-1, -3],
        [-2, -2],
        [-3, -1],
        [ 0, -3],
        [ 1, -3],
        [ 2, -2],
        [ 3, -1]]),
 array([[ 0,  4],
        [ 1,  4],
        [ 2,  3],
        [ 3,  2],
        [ 4,  0],
        [ 4, -1],
        [ 3, -2],
        [ 2, -3],
        [ 0, -4],
        [-1, -4],
        [-2, -3],
        [-3, -2],
        [ 0, -4],
        [ 1, -4],
        [ 2, -3],
        [ 3, -2]]),
 array([[ 0,  5],
        [ 1,  5],
        [ 2,  4],
        [ 3,  3],
        [ 5,  0],
        [ 5, -1],
        [ 4, -2],
        [ 3, -3],
        [ 0, -5],
        [-1, -5],
        [-2, -4],
        [-3, -3],
        [ 0, -5],
        [ 1, -5],
        [ 2, -4],
        [ 3, -3]]),
 array([[ 0,  6],
        [ 1,  6],
        [ 2,  5],
        [ 3,  4],
        [ 6,  0],
        [ 6, -1],
        [ 5, -2],
    